# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: node_js
node_js:
  - '8.10'

cache:
  directories:
    - node_modules

env:
  global:
    - NODE_ENV=test
    - CC_TEST_REPORTER_ID=9c4c59199acd9c2554329c7d3357064dc7a4e726e7e4fdc74f3e5ce22d6f36e9

before_script:
  - npm install -g yarn
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - yarn install

script:
  - yarn test:coverage

after_success:
  - ./cc-test-reporter format-coverage -t lcov --output coverage/codeclimate.jest.json coverage/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
  - ./cc-test-reporter upload-coverage

branches:
  only:
    - master
